Repository RUB-EP1/kmatrix-day-2025, pull requests merged in 2025-04, with the labels that each got.

#1 FEAT: create first website draft
  .cspell.json
  .editorconfig
  .envrc
  .gitattributes
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/clean-caches.yml
  .github/workflows/pr-linting.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  .prettierrc.yml
  .python-version
  .taplo.toml
  .vscode/extensions.json
  .vscode/settings.json
  LICENSE
  README.md
  docs/.gitignore
  docs/_quarto.yml
  docs/favicon.ico
  docs/images/banner.png
  docs/images/k-humans.svg
  docs/images/rub-white.svg
  docs/index.qmd
  docs/styles.css
  pixi.lock
  pixi.toml
  pyproject.toml
  uv.lock
Labels: ✨ Feature, 📝 Docs, 🖱️ DX

#6 ENH: add pole coupling plot and improve text
  .cspell.json
  docs/finding-poles.ipynb
  docs/index.qmd
  pyproject.toml
  uv.lock
Labels: 📝 Docs

#9 FEAT: embed Jupyter Lite server in website
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  docs/.gitignore
  docs/_quarto.yml
  docs/finding-poles.ipynb
  docs/index.qmd
  docs/references.bib
  docs/resources.qmd
  pyproject.toml
  uv.lock
Labels: ✨ Feature

#10 ENH: center web page contents
  docs/_quarto.yml
Labels: ⚙️ Enhancement

#4 FEAT: implement Julia notebook
  .cspell.json
  .editorconfig
  .envrc
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .taplo.toml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  docs/Manifest.toml
  docs/Project.toml
  docs/_quarto.yml
  docs/experimental-data.csv
  docs/images/1x1_production.svg
  docs/images/1x1_scattering.svg
  docs/index.qmd
  docs/k-matrix.jl
  pixi.lock
  pixi.toml
  pyproject.toml
  uv.lock
Labels: ✨ Feature

#11 ENH: finalize "Finding poles" notebook
  .cspell.json
  README.md
  docs/finding-poles-live.ipynb
  docs/finding-poles.ipynb
  docs/images/1x1-production.svg
  docs/images/1x1-scattering.svg
  docs/images/line-integral.svg
  docs/k-matrix.jl
  pyproject.toml
Labels: ⚙️ Enhancement, 📝 Docs

#5 FEAT: compute residues in 2-channel case
  .cspell.json
  docs/_quarto.yml
  docs/finding-poles-2channels.ipynb
  docs/finding-poles-live.ipynb
  docs/finding-poles.ipynb
  pyproject.toml
Labels: ✨ Feature

#14 FIX: update play button for 2-channel
  docs/finding-poles-2channels.ipynb
Labels: 🐛 Bug

#16 ENH: update julia notebook
  docs/k-matrix.jl
Labels: ⚙️ Enhancement, 🐛 Bug
